-- global_inventory

create table
  public.global_inventory (
    id integer generated by default as identity,
    num_green_potions integer not null default 0,
    num_green_ml integer null default 0,
    gold integer null default 100,
    blue_potions integer null default 0,
    blue_ml integer null default 0,
    red_potions integer null default 0,
    red_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

-- mypotiontypes
create table
  public.mypotiontypes (
    id integer generated by default as identity,
    name text null default '0'::text,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    cost integer null default 0,
    quantity integer null default 0,
    quantity_for_sale integer null default 0,
    constraint mypotiontypes_pkey primary key (id)
  ) tablespace pg_default;

-- carts
create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text null default '0'::text,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

-- cart_items
create table
  public.cart_items (
    customer_cart_id integer generated by default as identity,
    potion_type_id integer null,
    constraint cart_items_pkey primary key (customer_cart_id),
    constraint public_cart_items_customer_cart_id_fkey foreign key (customer_cart_id) references carts (cart_id),
    constraint public_cart_items_potion_type_id_fkey foreign key (potion_type_id) references mypotiontypes (id)
  ) tablespace pg_default;
