-- ledger
create table
  public.ledger (
    id integer generated by default as identity,
    gold integer null default 0,
    potions integer null default 0,
    ml integer null default 0,
    potion_type integer null,
    time time without time zone null default (now() at time zone 'PST'::text),
    description text null,
    constraint ledger_pkey primary key (id),
    constraint ledger_potion_type_fkey foreign key (potion_type) references mypotiontypes (id)
  ) tablespace pg_default;

-- global_inventory

create table
  public.global_inventory (
    id integer generated by default as identity,
    barrel_history integer null default 1,
    potion_history integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

-- mypotiontypes
create table
  public.mypotiontypes (
    id integer generated by default as identity,
    name text null default '0'::text,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    cost integer null default 0,
    constraint mypotiontypes_pkey primary key (id)
  ) tablespace pg_default;

-- carts
create table
  public.carts (
    cart_id integer generated by default as identity,
    customer_name text null default ''::text,
    time timestamp with time zone null default (now() at time zone 'pst'::text),
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id)
  ) tablespace pg_default;

-- cart_items
create table
  public.cart_items (
    customer_cart_id integer generated by default as identity,
    potion_type_id integer null,
    quantity integer null default 0,
    status integer null default 0,
    constraint cart_items_pkey primary key (customer_cart_id),
    constraint public_cart_items_customer_cart_id_fkey foreign key (customer_cart_id) references carts (cart_id),
    constraint public_cart_items_potion_type_id_fkey foreign key (potion_type_id) references mypotiontypes (id)
  ) tablespace pg_default;
